# Generated by Django 5.2.7 on 2025-10-26 05:10

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptoFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave_prod_serv', models.CharField(default='01010101', max_length=10)),
                ('clave_unidad', models.CharField(default='H87', max_length=10)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('unidad', models.CharField(default='Pieza', max_length=50)),
                ('descripcion', models.TextField()),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('importe', models.DecimalField(decimal_places=2, max_digits=12)),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'verbose_name': 'Concepto de Factura',
                'verbose_name_plural': 'Conceptos de Factura',
                'db_table': 'conceptos_factura',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio_fiscal', models.CharField(db_index=True, max_length=36, unique=True)),
                ('serie', models.CharField(default='A', max_length=10)),
                ('folio', models.IntegerField()),
                ('cliente_rfc', models.CharField(max_length=13)),
                ('cliente_nombre', models.CharField(max_length=200)),
                ('cliente_email', models.EmailField(max_length=254)),
                ('cliente_codigo_postal', models.CharField(max_length=5)),
                ('uso_cfdi', models.CharField(choices=[('G01', 'Adquisición de mercancías'), ('G02', 'Devoluciones, descuentos o bonificaciones'), ('G03', 'Gastos en general'), ('I01', 'Construcciones'), ('I02', 'Mobilario y equipo de oficina por inversiones'), ('I03', 'Equipo de transporte'), ('I04', 'Equipo de computo y accesorios'), ('I05', 'Dados, troqueles, moldes, matrices y herramental'), ('I06', 'Comunicaciones telefónicas'), ('I07', 'Comunicaciones satelitales'), ('I08', 'Otra maquinaria y equipo'), ('D01', 'Honorarios médicos, dentales y gastos hospitalarios'), ('D02', 'Gastos médicos por incapacidad o discapacidad'), ('D03', 'Gastos funerales'), ('D04', 'Donativos'), ('D05', 'Intereses reales efectivamente pagados por créditos hipotecarios (casa habitación)'), ('D06', 'Aportaciones voluntarias al SAR'), ('D07', 'Primas por seguros de gastos médicos'), ('D08', 'Gastos de transportación escolar obligatoria'), ('D09', 'Depósitos en cuentas para el ahorro, primas que tengan como base planes de pensiones'), ('D10', 'Pagos por servicios educativos (colegiaturas)'), ('P01', 'Por definir')], default='P01', max_length=3)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('status', models.CharField(choices=[('borrador', 'Borrador'), ('timbrada', 'Timbrada'), ('cancelada', 'Cancelada')], default='borrador', max_length=20)),
                ('xml_url', models.URLField(blank=True, null=True)),
                ('pdf_url', models.URLField(blank=True, null=True)),
                ('xml_file', models.FileField(blank=True, null=True, upload_to='facturas/xml/')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='facturas/pdf/')),
                ('fecha_timbrado', models.DateTimeField(blank=True, null=True)),
                ('fecha_cancelacion', models.DateTimeField(blank=True, null=True)),
                ('motivo_cancelacion', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('facturapi_id', models.CharField(blank=True, max_length=100, null=True)),
                ('facturapi_response', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'db_table': 'facturas',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
