# Generated by Django 5.2.7 on 2025-10-26 05:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facturacion', '0001_initial'),
        ('ventas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='factura',
            name='venta',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='factura', to='ventas.venta'),
        ),
        migrations.AddField(
            model_name='conceptofactura',
            name='factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conceptos', to='facturacion.factura'),
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['folio_fiscal'], name='facturas_folio_f_a36eda_idx'),
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['cliente_rfc'], name='facturas_cliente_b7c7d2_idx'),
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['status'], name='facturas_status_d57443_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='factura',
            unique_together={('serie', 'folio')},
        ),
    ]
