# Generated by Django 5.2.7 on 2025-10-26 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteGenerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('ventas', 'Ventas'), ('inventario', 'Inventario'), ('financiero', 'Financiero'), ('productos', 'Productos')], max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('archivo', models.FileField(upload_to='reportes/')),
                ('formato', models.CharField(max_length=10)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Reporte Generado',
                'verbose_name_plural': 'Reportes Generados',
                'db_table': 'reportes_generados',
                'ordering': ['-fecha_generacion'],
            },
        ),
    ]
